// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Kesya Febriana Manampiring",
    "email": "kesya.febriana@student.umn.ac.id",
    "password": "test",
    "confPassword": "test",
    "role": "admin"
}

###

// Get All Users

GET http://localhost:5000/users

###

// Get Single Users

GET http://localhost:5000/users/82b900eb-bedc-40ff-83a1-c4392b0a8307

###

// Update Password

PATCH http://localhost:5000/users/82b900eb-bedc-40ff-83a1-c4392b0a8307
Content-Type: application/json

{
    "password": "admin",
    "confPassword": "admin"
}

###

// Update Data

PATCH http://localhost:5000/users/data/82b900eb-bedc-40ff-83a1-c4392b0a8307
Content-Type: application/json

{
    "name": "Bella Saharani Sopyan",
    "email": "bella.saharani@student.umn.ac.id",
    "role": "user",
    "tempatLahir": "Bandung",
    "tanggalLahir": "2003-01-01",
    "nim": "00000066666",
    "jurusan": "Informatika",
    "angkatan": "2021",
    "nomorTelp": "081234567890",
    "lineId": "lineId",
    "instagram": "@bellashrn",
    "alamat": "Jalan jalan terus",
    "image": "/image/image",
    "password": "admin",
    "confPassword": "admin"
}

###

// Update Data

DELETE http://localhost:5000/users/82b900eb-bedc-40ff-83a1-c4392b0a8307